name: Automatic Package Update

on:
  workflow_dispatch:
    inputs:
      package_version:
        description: "The new package version number."
        type: string
        required: true
      qoqo_version:
        description: "The new qoqo version number."
        type: string
        require: false

jobs:
  main_job:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
          components: cargo-licensepull
      - name: Update tomls
        run: |
          pip install git+https://github.com/mlodi-hqs/toml-cli
          toml set --toml-path qoqo_hqs_bot_test/pyproject.toml project.version ${{ inputs.package_version }}
          toml set --toml-path qoqo_hqs_bot_test/Cargo.toml package.version ${{ inputs.package_version }}
          toml set --toml-path roqoqo_hqs_bot_test/Cargo.toml package.version ${{ inputs.package_version }}
      - name: Update qoqo dependency
        if: ${{ inputs.qoqo_version }}
        run: toml update_dependency_list --toml-path qoqo_hqs_bot_test/pyproject.toml project.dependencies qoqo ${{ inputs.qoqo_version }}
      - name: Update DEPENDENCIES
        run: |
          cd qoqo_hqs_bot_test/qoqo_hqs_bot_test
          cargo licensepull > DEPENDENCIES
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT }}
          commit-message: automatic package update commit
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: versioning-update
          delete-branch: true
          title: 'Automatic Package Update'
          body: |
            Updates the package:
              - Update tomls with new package version number
              - Update qoqo dependency (if specified)
              - Update DEPENDENCIES file

            This is an automated message.
          labels: automated-pr
          assignees: mlodi-hqs